sed \
  -e "s|__NEXT_PUBLIC_FIREBASE_API_KEY__|$NEXT_PUBLIC_FIREBASE_API_KEY|g" \
  -e "s|__NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN__|$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN|g" \
  -e "s|__NEXT_PUBLIC_FIREBASE_PROJECT_ID__|$NEXT_PUBLIC_FIREBASE_PROJECT_ID|g" \
  -e "s|__NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET__|$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET|g" \
  -e "s|__NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID__|$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID|g" \
  -e "s|__NEXT_PUBLIC_FIREBASE_APP_ID__|$NEXT_PUBLIC_FIREBASE_APP_ID|g" \
  -e "s|__NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID__|$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID|g" \
  firebase-config.template.js > firebase-config.js

echo "firebase-config.js created successfully."
